To-do app Vittoria
Technigo/project-todos-context-vite pull request #19
Opened 2024-04-13 17:50 UTC by vittoriamatteoli

## Netlify link
https://tasktide-app.netlify.app/

## Collaborators

[vittoriamatteoli]

2024-04-16 08:57 UTC, AntonellaMorittu requested changes
Hi Vittoria, congratulations for delivering an ambitious todo app! Super cool you used api requests to actually modify the state, brilliant! Your code is well structured and tidy and you also added moment.js into your implementation, nice touch! Now let's see some improvements that can be applied:
- the categories for the tasks are a bit difficult to remember, why not addind a name on hover on the icon or just add some text to the bottom besides the icon? I would also reduce the height of the webpage to fit the huge image, better to avoid scrolling if there's no tasks displayed.

To meet the basic requirements we need to fix a couple of things:
- Accessibility: scores 77, should get at leaast 95 👌 
- In mobile screen, the "+" buttons sometimes shows and sometimes is not int he UI, pls take a look at it
You worked solo and achieved a lot! Apply these little fixes and you're good to go ✨

2024-04-17 06:47 UTC, vittoriamatteoli commented
Hi Antonella, thanks for the suggestions regarding the categories and the image, I will adjust it later on, I've successfully fixed the app as per the requirements requested.
![95 + button ](https://github.com/Technigo/project-todos-context-vite/assets/144723838/08414e7c-0464-4953-b4c8-9c06fcef1eda)

2024-04-18 06:50 UTC, AntonellaMorittu requested changes
accessibility is fixed, lovely! Now I tested the app for responsiveness and there is a quite big horizontal scrolling on all screen sizes, that needs to be removed, and did you test the "+" button and worked? I still can't see it on any mobile screen, please take a look at it again ☺️ 
<img width="378" alt="Screenshot 2024-04-18 at 08 48 17" src="https://github.com/Technigo/project-todos-context-vite/assets/33493978/3967d255-c9b8-4813-914d-fb4d27894c76">

2024-04-18 09:17 UTC, vittoriamatteoli commented
Hi Antonella, sorry I didn't understand was not rendering just when are not tasks available, I'll fix that 🙏🏻

2024-04-18 09:33 UTC, vittoriamatteoli commented
Could you check now if works all fine?
![Screenshot 2024-04-18 113029](https://github.com/Technigo/project-todos-context-vite/assets/144723838/d2f5fd4f-b372-4ef2-aab5-be5f2b14171d)
![Screenshot 2024-04-18 113102](https://github.com/Technigo/project-todos-context-vite/assets/144723838/7ddc0017-ad41-4e7b-944d-1a196fb9bfb1)

2024-05-03 12:02 UTC, AntonellaMorittu approved these changes

2026-01-27 13:34 UTC, closed without merging